// The model viewer's strings (#/models), apart from strings.ts so that they load with the
// viewer and not with every page. Same rules as strings.ts: another language is one more
// object of the same shape.

const en = {
  heading: "Models",
  intro:
    "Machine models made for the pack's own mods, as the game's shape files hold them and moved by their rigs. Turn the inputs, fit and remove parts, and click any piece to see what it is called.",
  none: "No models have been published.",
  loadFailed: "Could not load the list of models.",
  filesFailed: "Could not load this model's files.",
  unknown: (id: string) => `There is no model “${id}”.`,
  allModels: "All models",
  counts: (elements: number, parts: number) =>
    `${elements.toLocaleString("en")} element${elements === 1 ? "" : "s"}` + (parts > 0 ? `, ${parts} rig part${parts === 1 ? "" : "s"}` : ", no rig"),
  credit: "Credit",
  creditMore: "Credits and terms",
  source: "Source files",
  shapeFile: "shape",
  rigFile: "rig",
  noWebgl:
    "This browser could not start WebGL, so the model cannot be drawn. The controls and the element list still work: pick an element from the list to see its details.",
  viewerFailed: "The 3D viewer could not be loaded. Reload the page to try again.",
  loadingViewer: "Loading the 3D view…",
  stageLabel: (title: string) => `3D view of the ${title} model. Drag to orbit, right-drag or two fingers to pan, scroll or pinch to zoom.`,
  views: "Camera",
  viewNames: { angled: "Angled", opposite: "Opposite", front: "Front", side: "Side", top: "Top", reset: "Reset" },
  motion: "Motion",
  shaftAngle: "Shaft angle θ",
  shaftTravel: (deg: number) => `travel ${deg.toLocaleString("en")}°`,
  depth: "Depth",
  lifting: "Lifting",
  reverse: "Turn backwards",
  feedTravel: (deg: number) => `feed φ ${deg.toLocaleString("en")}°`,
  trunkTravel: "Trunk travel T",
  blocks: (t: number, end: number) => `${t.toFixed(2)} / ${end.toFixed(2)} blocks`,
  trunkSize: "Trunk",
  sizeNames: ["None", "Thin", "Thick"],
  presence: "Trunk presence p",
  play: "Play",
  pause: "Pause",
  playHintScript: "Runs the model's cycle non-stop.",
  playHintTurn: "Turns the shaft.",
  posedByHand: "Posed by hand",
  paused: (phase: string) => `Paused: ${phase}`,
  fitted: "Fitted parts",
  prop: "Prop",
  propNone: "None",
  overlays: "Overlays",
  overlayCells: "Block cells",
  overlayCollision: "Collision boxes",
  overlayEdges: "Box edges",
  colour: "Colour",
  colourByPart: "Rig part",
  colourByTexture: "Texture",
  parts: "Parts",
  textures: "Textures",
  always: "always",
  needs: (what: string) => `needs ${what}`,
  rides: (part: string) => `rides ${part}`,
  unmatched: "unmatched",
  elementsOf: (n: number) => `${n} element${n === 1 ? "" : "s"}`,
  pickHint: "Hover to preview an element; click or tap it, or pick it from the list, to pin its details here. Esc clears.",
  part: "part",
  texture: "texture",
  rotation: "rotation",
  origin: "origin",
  copyName: "Copy name",
  copyPart: "Copy part id",
  copied: "Copied",
  copySelect: "Selected: press Ctrl+C",
  clear: "Clear",
  unrecognised: (keys: string) => `Rig keys not drawn: ${keys}`,
};

export type ModelStrings = typeof en;
export const mt: ModelStrings = en;
