// The model viewer's strings (#/models), apart from strings.ts so that they load with the
// viewer and not with every page. Same rules as strings.ts: another language is one more
// object of the same shape.

const en = {
  heading: "Models",
  intro:
    "Machine models made for the pack's own mods, as the game's shape files hold them, moved by their rigs and their own animations. Turn the inputs, fit and remove parts, and click any piece to see what it is called.",
  none: "No models have been published.",
  loadFailed: "Could not load the list of models.",
  filesFailed: "Could not load this model's files.",
  unknown: (id: string) => `There is no model “${id}”.`,
  allModels: "All models",
  counts: (elements: number, parts: number) =>
    `${elements.toLocaleString("en")} element${elements === 1 ? "" : "s"}` + (parts > 0 ? `, ${parts} rig part${parts === 1 ? "" : "s"}` : ", no rig"),
  credit: "Credit",
  creditMore: "Credits and terms",
  source: "Source files",
  shapeFile: "shape",
  rigFile: "rig",
  bogieFile: "bogie",
  noWebgl:
    "This browser could not start WebGL, so the model cannot be drawn. The controls and the element list still work: pick an element from the list to see its details.",
  viewerFailed: "The 3D viewer could not be loaded. Reload the page to try again.",
  loadingViewer: "Loading the 3D view…",
  stageLabel: (title: string) => `3D view of the ${title} model. Drag to orbit, right-drag or two fingers to pan, scroll or pinch to zoom.`,
  views: "Camera",
  viewNames: { angled: "Angled", opposite: "Opposite", front: "Front", side: "Side", top: "Top", reset: "Reset" },
  motion: "Motion",
  shaftAngle: "Shaft angle θ",
  shaftTravel: (deg: number) => `travel ${deg.toLocaleString("en")}°`,
  turnOf: (turn: number, turns: number) => `turn ${turn} of ${turns}`,
  ofCycle: (percent: number, cycle: string) => `${percent} % of the ${cycle}`,
  rolled: (blocks: number) => `${blocks.toFixed(2)} blocks rolled`,
  cycleDistance: (cycle: string, turns: number, blocks: number) => `a ${cycle} is ${turns} turns, ${blocks.toFixed(2)} blocks of track`,
  blocksPerSecond: (v: number) => `${v.toFixed(1)} blocks/s`,
  depth: "Depth",
  lifting: "Lifting",
  reverse: "Turn backwards",
  feedTravel: (deg: number) => `feed φ ${deg.toLocaleString("en")}°`,
  trunkTravel: "Trunk travel T",
  workOf: (name: string) => `${name.charAt(0).toUpperCase()}${name.slice(1)}`,
  workClass: "Class",
  workPresence: "Presence p",
  inputSpeed: "Input speed",
  rps: (v: number) => `${v.toFixed(2)} RPS`,
  travelOf: (t: number, end: number, unit: string) => `${t.toFixed(2)} / ${end.toFixed(2)} ${unit}`,

  trunkSize: "Trunk",
  sizeNames: ["None", "Thin", "Thick"],
  presence: "Trunk presence p",
  play: "Play",
  pause: "Pause",
  playHintScript: "Runs the model's cycle non-stop.",
  playHintTurn: "Turns the shaft.",
  playHintGeared: "Turns the shaft; the job moves on with it, to its end.",
  playHintRoll: "Rolls it along the track at the input speed.",
  rolling: "Rolling",
  oil: "Oil",
  posedByHand: "Posed by hand",
  paused: (phase: string) => `Paused: ${phase}`,
  animation: "Animation",
  animationNone: "None (at rest)",
  animationOther: "Other",
  animationFrame: "Frame",
  frameOf: (frame: number, last: number) => `${frame} / ${last}`,
  animationSpeed: "Speed",
  animationSpeedOf: (speed: number) => `${speed.toFixed(2)}×, ${Math.round(speed * 30 * 100) / 100} frames/s`,
  animationLoop: "Loop",
  animationLength: (frames: number, seconds: number) => `${frames} frame${frames === 1 ? "" : "s"}, ${seconds.toFixed(2)} s at speed 1`,
  animationEnds: {
    Repeat: "In the game it repeats.",
    Hold: "In the game it holds its last frame.",
    Stop: "In the game it stops after its last frame, back at rest.",
    EaseOut: "In the game it eases out after its last frame.",
  } as Record<string, string>,
  animationHint: "The shape's own keyframes, posed as the game poses them, 30 frames a second at speed 1. Stopped, the frame slider poses it.",
  fitted: "Fitted parts",
  stateByHand: "As ticked below",
  stateNeeds: (what: readonly string[]) =>
    `Waits for ${what.length > 1 ? `${what.slice(0, -1).join(", ")} and ${what.at(-1)}` : (what[0] ?? "")}: none of this is drawn until ${what.length > 1 ? "they are" : "it is"} fitted.`,
  prop: "Prop",
  propNone: "None",
  overlays: "Overlays",
  overlayCells: "Block cells",
  overlayCollision: "Collision boxes",
  overlayEdges: "Box edges",
  overlayTrack: "Track",
  trackNote: "The track is a backdrop: its sleepers scroll by the distance rolled while the vehicle stays put.",
  bogiesNote: "the bogies, drawn where the renderer puts them",
  colour: "Colour",
  colourByPart: "Rig part",
  colourByTexture: "Texture",
  parts: "Parts",
  textures: "Textures",
  always: "always",
  needs: (what: string) => `needs ${what}`,
  rides: (part: string) => `rides ${part}`,
  unmatched: "unmatched",
  elementsOf: (n: number) => `${n} element${n === 1 ? "" : "s"}`,
  pickHint: "Hover to preview an element; click or tap it, or pick it from the list, to pin its details here. Esc clears.",
  part: "part",
  texture: "texture",
  rotation: "rotation",
  origin: "origin",
  copyName: "Copy name",
  copyPart: "Copy part id",
  copied: "Copied",
  copySelect: "Selected: press Ctrl+C",
  clear: "Clear",
  unrecognised: (keys: string) => `Rig keys not drawn: ${keys}`,
};

export type ModelStrings = typeof en;
export const mt: ModelStrings = en;
