// Every UI string, so another language is one more object of the same shape. Item
// names and descriptions come from the export, which is English only for now.

export const REPO_URL = "https://github.com/benjamin-kirkbride/Seraph-Horizons";
export const NEW_ISSUE_URL = `${REPO_URL}/issues/new`;

/** A tooltip lists this many of a row's codes; a termite mound has 148. */
const VARIANTS_SHOWN = 20;

const en = {
  siteTitle: "Seraph Horizons recipes",
  skipToContent: "Skip to content",
  unofficial:
    "Unofficial fan-made reference for the Seraph Horizons modpack. Not affiliated with or endorsed by Anego Studios.",
  searchLabel: "Search items",
  searchPlaceholder: "Search by name or code, e.g. copper ingot",
  searchButton: "Search",
  versionLabel: "Pack version",
  themeLabel: "Theme",
  themes: { system: "System", light: "Light", dark: "Dark" },
  loading: "Loading…",
  loadFailed: "Could not load the data for this page.",
  noVersions: "No data has been published yet.",
  unknownVersion: (v: string) => `There is no version “${v}”.`,
  notFound: "There is nothing at this address.",
  backHome: "Back to the start page",
  homeIntro: (items: number, recipes: number, pack: string, game: string) =>
    `${items.toLocaleString("en")} items and ${recipes.toLocaleString("en")} recipes from Seraph Horizons ${pack} on Vintage Story ${game}.`,
  homeHint: "Search for an item to see how it is made and what it is used for.",
  recipeTypesHeading: "Recipe types",
  typeNotInVersion: (code: string, version: string) => `There are no recipes of type ${code} in version ${version}.`,
  typeShowing: (first: number, last: number, total: number) =>
    `Recipes ${first.toLocaleString("en")}–${last.toLocaleString("en")} of ${total.toLocaleString("en")}`,
  recipesLabel: "Recipes",
  pagesLabel: "Pages",
  previousPage: "Previous",
  nextPage: "Next",
  pageOf: (page: number, pages: number) => `Page ${page} of ${pages}`,
  entitiesLink: "Creatures and traders",
  entitiesHomeLink: (n: number) => `Browse ${n.toLocaleString("en")} kinds of creature and trader and what they drop or trade.`,
  entitiesHeading: "Creatures and traders",
  entitiesIntro:
    "Every creature that drops or can be harvested for something, and every trader, as far as the game's data declares it. Drops decided in code are not listed.",
  entitiesFilter: "Filter",
  entitiesFilterPlaceholder: "Name or code, e.g. wolf",
  entitiesNone: (q: string) => `No creature or trader matches “${q}”.`,
  creatures: "Creatures",
  traders: "Traders",
  entityCounts: (variants: number, drops: number, trades: number) =>
    [
      variants > 1 ? `${variants} variants` : "",
      drops ? `${drops} item${drops === 1 ? "" : "s"} dropped` : "",
      trades ? `${trades} item${trades === 1 ? "" : "s"} traded` : "",
    ]
      .filter(Boolean)
      .join(", "),
  variantsLabel: "Variants",
  allVariants: "All variants",
  allVariantsHint: (n: number) => `Every item the ${n} variants give, with the range of amounts. Pick a variant for its own list.`,
  everyVariant: "all",
  someVariants: (n: number, total: number) => `${n} of ${total}`,
  entityNotInVersion: (code: string, version: string) => `${code} gives nothing in version ${version}, or does not exist there.`,
  entitySections: {
    drops: "Drops when killed",
    harvest: "Harvested from the body",
    sells: "Sells",
    buys: "Buys",
  },
  item: "Item",
  stock: "Stock",
  perTrade: "Per trade",
  priceHeading: "Price in rusty gears",
  resultsFor: (q: string, n: number, more: boolean) =>
    `${more ? "More than " : ""}${n.toLocaleString("en")} result${n === 1 ? "" : "s"} for “${q}”`,
  noResults: (q: string) => `Nothing matches “${q}”.`,
  hiddenInHandbook: "not in handbook",
  code: "Code",
  mod: "Mod",
  kind: "Kind",
  description: "Description",
  attributes: "Properties",
  sources: "Other sources",
  gives: "Gives",
  madeBy: "Made by",
  usedIn: "Used in",
  noRecipesMake: "No recipe makes this item.",
  noRecipesUse: "No recipe uses this item.",
  smeltedFrom: "Obtained by heating",
  smeltsInto: "Heating it gives",
  itemNotInVersion: (code: string, version: string) => `${code} is not in version ${version}.`,
  keptItem: (code: string) => `Showing ${code} in the version you picked.`,
  lostItem: (code: string) => `${code} does not exist in that version, so you are on its start page.`,
  showMore: (n: number) => `Show ${n} more`,
  recipeCount: (n: number) => `${n.toLocaleString("en")} recipe${n === 1 ? "" : "s"}`,
  variantOf: (i: number, n: number) => `Variant ${i} of ${n}`,
  previousVariant: "Previous variant",
  nextVariant: "Next variant",
  pause: "Pause",
  play: "Play",
  shapeless: "Shapeless: any arrangement works",
  tool: "Tool",
  toolNote: (cost: number | undefined) => (cost ? `tool, loses ${cost} durability` : "tool, not consumed"),
  returns: (name: string) => `returns ${name}`,
  output: "Output",
  ingredients: "Ingredients",
  layer: "Layer",
  layerOf: (i: number, n: number) => `Layer ${i} of ${n}`,
  filledCells: (n: number) => `${n} filled`,
  voxelGrid: (w: number, h: number) => `${w} by ${h} pattern`,
  sealFor: (h: number) => `Seal for ${h} hour${h === 1 ? "" : "s"}`,
  noSeal: "Mixes instantly, no sealing",
  cooksInto: "Cooks into",
  dirtyPot: "Leaves the pot dirty",
  requirements: "Requirements",
  buildInPlace: "Place the block, then right-click it with each stage's items in your hotbar.",
  stage: (n: number) => `Stage ${n}`,
  stages: "Stages",
  placed: "Place it",
  construct: "Construct",
  rightClick: (action: string) => `Right-click: ${action}`,
  totalNeeded: "In total",
  butcheryFor: "For",
  butcheryHeading: "Butchery",
  butcherySteps: {
    pickUp: "Pick up the body with an empty hand",
    skin: "Skin it on a hook",
    bleed: "Leave it on the hook to bleed out",
    butcher: "Butcher it on a table",
    harvest: "Or harvest it where it lies",
  },
  butcheryGives: "Gives",
  butcheryOr: "or",
  butcheryHours: (h: number) => `Takes ${h} in-game hour${h === 1 ? "" : "s"}`,
  butcheryOptional: "Optional",
  butcheryNeeds: (names: string) => `only with ${names}`,
  butcheryEfficiency: (min: string, max: string) => (min === max ? `yield ×${min}` : `yield ×${min} to ×${max}, by type`),
  butcheryHarvestCut: (share: string) => `The Butchering mod leaves ${share} of what harvesting would give; the amounts below account for that.`,
  butcheryScaled: {
    efficiency: "times the station's yield",
    condition: "times the creature's condition",
  },
  butcheryStationHint: "Each station multiplies it by its yield:",
  butcheryStationYield: (name: string, multiplier: string) => `${name}: ×${multiplier}`,
  butcheryConditionHint: (range: { min: string; max: string } | null) =>
    `The creature's condition is its weight${range ? `, from ×${range.min} at the lowest to ×${range.max} when well fed` : ""}. ` +
    "It puts weight on by eating and loses it in freezing weather once it has gone months without food; " +
    "with the world's harsh winters turned off, every creature is well fed.",
  butcheryYieldGround: "Harvested where it lies",
  butcheryYieldFull: "Hook and table",
  butcheryYieldWeight: (lowest: boolean) => (lowest ? "Low" : "Good"),
  butcheryYieldWeightSuffix: " weight",
  butcheryYieldNone: "none",
  butcheryYieldsNote: (o: { share?: string; low?: string; high?: string; stations: string[]; ranges: boolean }) =>
    [
      `Harvested where it lies is what the Butchering mod leaves of the usual harvest${o.share ? ` (${o.share})` : ""}.`,
      o.low && o.high
        ? `Low and good are the creature's weight, which multiplies food (and the like) by ×${o.low} to ×${o.high}.`
        : "Food (and the like) depends on the creature's weight; these amounts are for a well-fed one.",
      o.stations.length > 0 ? `Hook and table amounts are at a station yield of ×1; ${o.stations.join(" and ")}, by type.` : "",
      `Amounts are averages${o.ranges ? ", or the range of the creatures' averages" : ""}; the butchery cards below give the spread.`,
    ]
      .filter(Boolean)
      .join(" "),
  butcheryStationRange: (step: string, min: string, max: string) =>
    `${step === "skin" ? "hooks" : step === "butcher" ? "tables" : step} give ${min === max ? `×${min}` : `×${min} to ×${max}`}`,
  butcheryNote: "Amounts are averages ± spread, before the station's yield and the creature's condition (a starving one gives less meat).",
  butcheryOnEntity: "Carry the body to a hook and a table for the full yield, or harvest it in the field for less.",
  transitionVerbs: {
    perish: "Spoils",
    dry: "Dries",
    cure: "Cures",
    ripen: "Ripens",
    melt: "Melts",
    harden: "Hardens",
    burn: "Burns",
    convert: "Turns",
    smoke: "Smoked",
  } as Record<string, string>,
  transitionVerb: "Turns",
  transitionOn: "station",
  transitionDone: (verb: string, when: string) => `${verb} after ${when} of game time`,
  transitionSteps: (starts: string, takes: string) => `${starts} before it starts, then ${takes}`,
  transitionRate:
    "At the usual rate, in an inventory, a chest or on the ground. Where it is kept can change that: a cellar slows spoiling, and some containers speed drying or stop it. Once a stack has started to spoil, it no longer dries or cures.",
  transitionRatio: (ratio: string) => `Stack size ×${ratio}`,
  tubDone: (kind: string, when: string) =>
    kind === "rust" ? `Rusts through in ${when} of game time` : kind === "pickle" ? `Pickled clean in ${when} of game time` : kind === "passivate" ? `Passivated in ${when} of game time` : `Done in ${when} of game time`,
  tubBatch: (n: number, litres: number | undefined) =>
    `A batch of up to ${n} gear${n === 1 ? "" : "s"}${litres ? `; a finished batch uses up ${litres} L` : ""}`,
  tubEats: (grace: string, every: string) =>
    `Take them out within ${grace} of done: after that the liquid eats one gear every ${every}`,
  tubLossChance: (chance: string) => `${chance} of the gears come out lost`,
  tubLost: "a lost gear becomes",
  tubRoles: { batch: "the batch", liquid: "the liquid", station: "in" } as Record<string, string>,
  lotteryTrigger: (trigger: string) =>
    trigger === "inventory" ? "Each one is decided the moment it lands in a player's inventory:" : "Each one is decided by chance:",
  lotteryNothing: "nothing",
  lotteryOutcomes: "Outcomes",
  machineTurns: (power: string, turns: string, work?: { amount: string; unit: string; per?: number }) =>
    power === "hand" && work?.unit === "blows"
      ? `By hand: ${turns} blows a job, each a right-click with a hammer`
      : power === "hand" && work?.unit === "strokes"
      ? `By hand: ${turns} ${turns === "1" ? "stroke" : "strokes"} of the treadle a job, a stroke a second while right-click is held`
      : (power === "hand"
          ? `By hand: ${turns} turns of the lever a job, a turn a second while right-click is held`
          : `${power === "mechanical" ? "Mechanical power" : power}: ${turns} turns of the axle a job`) +
        (work ? ` (${work.amount} ${work.unit}${work.per ? `, ${work.per} turns each` : ""})` : ""),
  machineOil: (points: string, tank: number | undefined, litres: string) =>
    `Drains ${points} points of oil (${litres} L) from the machine's tank${tank ? ` of ${tank}` : ""} a job`,
  machineNotes: {
    kept: "kept: fitted, never consumed",
    oil: "fills the oil tank",
    station: "the machine",
    consumed: "",
  } as Record<string, string>,
  machineWear: (cost: number | undefined, rule: string | undefined) =>
    `tool, loses ${cost ?? 0} durability a job` +
    (rule === "dividedByOilFill" ? " with a full oil tank; divided by the tank's fill, so an empty tank breaks it" : ""),
  madeByElsewhere: (n: number, type: string) =>
    `${n.toLocaleString("en")} item${n === 1 ? " turns" : "s turn"} into this by ${type.toLowerCase()}, not listed here: each one's own page shows it under “Used in”.`,
  ratio: "Share",
  amount: "Amount",
  slot: "Slot",
  from: "From",
  source: "Defined in",
  empty: "empty",
  nothingMatches: "nothing registered matches",
  row: (r: number, c: number) => `row ${r}, column ${c}`,
  credits: "Credits",
  creditsIntro:
    "Everything shown here comes from these mods and from the game itself, exported from a server running the pack. All names, text and images belong to their authors.",
  by: "by",
  unknownAuthors: "authors not listed",
  website: "website",
  about: "About",
  aboutText:
    "This site is an unofficial fan project for the Seraph Horizons modpack. It is not made by, affiliated with or endorsed by Anego Studios, the developers of Vintage Story, or by the authors of the mods listed above.",
  removal: "Removal requests",
  removalText: "If you are the author of anything shown here and want it changed or removed, open an issue on the GitHub repository:",
  removalLink: "open an issue",
  sourceCode: "Source on GitHub",
  sourceKinds: {
    blockDrop: "Dropped by block",
    entityDrop: "Dropped by creature",
    traderSells: "Sold by trader",
    traderBuys: "Bought by trader",
    other: "Other",
  },
  // Kinds for sources of type `other`, by the export's note; the note then goes unsaid.
  sourceNotes: { Panned: "Panning", Harvested: "Harvested" } as Record<string, string>,
  // The same kinds on the page of the block that gives the item.
  giveKinds: { blockDrop: "When broken", other: "Other" } as Record<string, string>,
  giveNotes: { Panned: "When panned", Harvested: "When harvested" } as Record<string, string>,
  panChance: "Chance on each pan",
  scalesWithStat: (stat: string) => `chance scales with player stat ${stat}`,
  andMore: (n: number) => `and ${n} more`,
  quantity: "Quantity",
  price: (gears: number) => `${gears} rusty gear${gears === 1 ? "" : "s"}`,
  attr: {
    maxStackSize: "Stack size",
    durability: "Durability",
    tool: "Tool type",
    toolTier: "Tool tier",
    requiredMiningTier: "Mining tier needed",
    attackPower: "Attack power",
    materialDensity: "Density",
    nutrition: "Nutrition",
    fertilizer: "Fertilizer",
    burn: "Fuel",
    smelting: "Heating",
    storageFlags: "Storage",
  },
  densityHint: (density: number) =>
    `${density <= 1000 ? "Floats" : "Sinks"} in water. Water's density is 1000: dropped items at or below it float, heavier ones sink.`,
  placeholderIcon: "no icon",
  gears: "rusty gears",
  gearsPerLitre: "rusty gears per litre",
  /** After a liquid's value, on screen. */
  perLitre: "/ L",
  perLitreHint: "Rusty gears per litre.",
  noTradeValue: "No trade value",
  floorZeroHint: "Worth less than a rusty gear per full stack, so traders treat it as worthless.",
  valueSwitchesHint: (names: string[]) => `With the default config. Depends on ${names.join(", ")}.`,
  sortLabel: "Order",
  searchSorts: { best: "Best match", "value-asc": "Value, lowest first", "value-desc": "Value, highest first" },
  valuesLink: "Values",
  valuesHomeLink: (n: number) => `See what ${n.toLocaleString("en")} items are worth in rusty gears.`,
  valuesHeading: "Item values",
  valuesIntro:
    "What every item is worth to the pack's traders, in rusty gears, with the pack's default config. A value shown dimmed is under a gear for a whole stack, which traders treat as worthless. Liquids are priced per litre, marked “/ L”.",
  valuesNone: "This version has no item values.",
  valuesFilter: "Filter",
  valuesFilterPlaceholder: "Name, code or mod, e.g. copper",
  valuesUnvalued: "Include items with no value",
  valuesCount: (n: number) => `${n.toLocaleString("en")} row${n === 1 ? "" : "s"}`,
  valuesRowCount: (rows: number, items: number) =>
    `${rows.toLocaleString("en")} row${rows === 1 ? "" : "s"}, ${items.toLocaleString("en")} item${items === 1 ? "" : "s"}`,
  valuesGroupedNote:
    "Variants the game shows as one tile in the creative menu and the handbook share a row when they are worth the same, as do a block's orientations; open a row to list them.",
  valuesVariants: (n: number, total: number) =>
    n === total ? `${n.toLocaleString("en")} variants` : `${n.toLocaleString("en")} of ${total.toLocaleString("en")} variants`,
  valuesVariantsHint: (codes: readonly string[], grouped: boolean) =>
    `${grouped ? "One tile in the creative menu, worth the same" : "Same name, mod and value"}:\n${codes.slice(0, VARIANTS_SHOWN).join("\n")}${codes.length > VARIANTS_SHOWN ? `\nand ${codes.length - VARIANTS_SHOWN} more` : ""}`,
  valuesNoMatch: (q: string) => `No item matches “${q}”.`,
  valuesNoMatchFilters: "No item matches these filters.",
  valuesKind: "Kind",
  valuesKinds: { all: "All", items: "Items", blocks: "Blocks", liquids: "Liquids" },
  valuesWorthless: "Worthless",
  valuesUnlisted: "Not in handbook",
  valuesFlagFilters: { any: "Shown", only: "Only", hide: "Hidden" },
  valuesColumns: { name: "Item", mod: "Mod", value: "Value" },
  sortBy: (column: string) => `Sort by ${column.toLowerCase()}`,
  modelsLink: "Models",
  powerLink: "Power",
  power: {
    heading: "Mechanical power",
    intro:
      "What every power source on a mechanical network gives and what every machine takes, with the pack's default config, read from the running game.",
    none: "This version's export has no power data.",
    sections: { overview: "Overview", producers: "Producers", wind: "Wind", explorer: "Load explorer", consumers: "Consumers" },
    units:
      "Figures are in the network's own units: speed is the network speed, torque and load are what the game adds up on a shaft, and power is torque × speed. The kN a windmill's block info shows is a cosmetic readout of the same torque, listed only for comparison.",
    reference: (name: string, load: string) => `For scale, one ${name.toLowerCase()} working is a load of ${load}.`,
    referenceNone: "This export lists no helve hammer to compare loads with.",
    families: { wind: "Wind", water: "Water", steam: "Steam", muscle: "Muscle" },
    categories: { machine: "Machine", transmission: "Transmission", brake: "Brake" },
    cols: {
      name: "Name",
      mod: "Mod",
      family: "Family",
      free: "Free speed",
      stall: "Stall torque",
      peak: "Peak power",
      kn: "In-game kN",
      conditions: "Conditions",
      cost: "Cost",
      category: "Kind",
      load: "Load",
      idle: "Idle",
      dry: "Dry",
      note: "Note",
      pattern: "Pattern",
      strength: "Strength",
      duration: "Lasts",
      share: "Share of time",
      gusts: "Gusts",
      avgPeak: "Average peak power",
      ofFull: "Of full wind",
      avgFree: "Average free speed",
      producer: "Producer",
      speed: "Speed",
      avgSpeed: "Average speed",
      stalled: "Time stalled",
      count: "Count",
    },
    producersNote: "Windmills at full wind with the sails listed; each figure assumes one producer turning a shaft alone, without gearing.",
    torqueTitle: "Torque against network speed",
    torqueDesc: (wind: string) =>
      `Each line is one producer: the torque it gives at each network speed. Windmills are drawn at wind ${wind}. A network settles where the torque meets its load.`,
    peakTitle: "Peak power",
    peakDesc: "Torque × speed at its best, for each producer shown above.",
    showFamilies: "Show",
    windControl: "Wind",
    windFull: "full",
    sailsControl: "Sails",
    sailsAsListed: "As listed",
    speedAxis: "Network speed",
    torqueAxis: "Torque",
    powerAxis: "Power",
    shareAxis: "Share of time",
    windAxis: "Wind speed",
    atSpeed: (s: string) => `At speed ${s}`,
    chartKeys: "Use the left and right arrow keys to move along the speed axis.",
    noneShown: "No producer is shown; tick a family above.",
    fallback: "default",
    fallbackHint: "The exporter could not read this value from the game and used its built-in default.",
    sourcesSummary: (n: number, fallbacks: number) =>
      `Where these numbers come from (${n} source${n === 1 ? "" : "s"}${fallbacks ? `, ${fallbacks} default${fallbacks === 1 ? "" : "s"}` : ""})`,
    noWind: "This export has no wind simulation.",
    windIntro: (years: number, perHour: number, seed: number) =>
      `The game's own weather code, run for ${years} game year${years === 1 ? "" : "s"} at ${perHour} sample${perHour === 1 ? "" : "s"} an hour (seed ${seed}). Wind gets stronger with height above sea level; below sea level the game weakens it, which this page does not model.`,
    heightControl: "Height above sea level",
    blocks: (h: number) => (h === 0 ? "sea level" : `${h} blocks`),
    histTitle: (h: string) => `Wind speed at ${h}`,
    histDesc: "Share of time the wind blows at each speed. The line marks 0.6, where a vanilla windmill reaches its cap.",
    windStats: (mean: string, atLeast: string) => `Mean wind ${mean}; at least 0.6 for ${atLeast} of the time.`,
    windAveragesTitle: "Windmills averaged over time",
    windAveragesNote: "Peak power and free speed at each wind, weighted by how long the wind blows that hard. Turbulence from nearby windmills is not counted.",
    turbulence: "Halved by another windmill within 1.5 × its sails",
    yes: "Yes",
    no: "No",
    duration: (mean: string, min: string, max: string) => (min === max ? `${mean} h` : `${mean} h on average (${min}–${max} h)`),
    showMods: "Mods",
    explorerIntro:
      "Pick the machines on one shaft. Each producer is then put to that load alone: the speed it settles at, or whether it stalls. A ranged load counts its high end.",
    machine: "Machine",
    count: "How many",
    addMachine: "Add a machine",
    remove: "Remove",
    removeRow: (name: string) => `Remove ${name}`,
    presets: "Quick picks",
    presetHammers: "4 helve hammers",
    presetQuern: "1 quern",
    clear: "Clear",
    dry: "Machines run dry (no oil)",
    dryHint: (n: number) => `A machine with an oil tank takes more when it runs dry: up to ×${n} here.`,
    totalLoad: (load: string) => `Total load ${load}`,
    explorerTitle: "Speed under this load",
    explorerDesc: (h: string) => `Equilibrium speed of each producer under the total load. Windmills twice: averaged over the wind at ${h}, and at full wind.`,
    atFull: "full wind",
    averaged: "averaged",
    stalls: "Stalls",
    stalledShare: (p: string) => `stalled ${p} of the time`,
    emptyLoad: "Add a machine to see what each producer can turn.",
    consumersTitle: "Load by machine",
    consumersDesc: "What each machine takes while working, grouped by mod.",
    legendLoad: "Load",
    legendRange: "Up to (ranged)",
    legendDry: "Dry",
    transmission: (n: number) => `Transmission and brakes (${n})`,
    range: (a: string, b: string) => `${a}–${b}`,
    table: "Table",
  },
  multiblocksLink: "Multiblocks",
  multiblocksHomeLink: (n: number) => `See the ${n.toLocaleString("en")} structures built block by block, layer by layer.`,
};

export type Strings = typeof en;
export const t: Strings = en;
