// Every UI string, so another language is one more object of the same shape. Item
// names and descriptions come from the export, which is English only for now.

export const REPO_URL = "https://github.com/benjamin-kirkbride/Seraph-Horizons";
export const NEW_ISSUE_URL = `${REPO_URL}/issues/new`;

const en = {
  siteTitle: "Seraph Horizons recipes",
  skipToContent: "Skip to content",
  unofficial:
    "Unofficial fan-made reference for the Seraph Horizons modpack. Not affiliated with or endorsed by Anego Studios.",
  searchLabel: "Search items",
  searchPlaceholder: "Search by name or code, e.g. copper ingot",
  searchButton: "Search",
  versionLabel: "Pack version",
  themeLabel: "Theme",
  themes: { system: "System", light: "Light", dark: "Dark" },
  loading: "Loading…",
  loadFailed: "Could not load the data for this page.",
  noVersions: "No data has been published yet.",
  unknownVersion: (v: string) => `There is no version “${v}”.`,
  notFound: "There is nothing at this address.",
  backHome: "Back to the start page",
  homeIntro: (items: number, recipes: number, pack: string, game: string) =>
    `${items.toLocaleString("en")} items and ${recipes.toLocaleString("en")} recipes from Seraph Horizons ${pack} on Vintage Story ${game}.`,
  homeHint: "Search for an item to see how it is made and what it is used for.",
  recipeTypesHeading: "Recipe types",
  entitiesLink: "Creatures and traders",
  entitiesHomeLink: (n: number) => `Browse ${n.toLocaleString("en")} kinds of creature and trader and what they drop or trade.`,
  entitiesHeading: "Creatures and traders",
  entitiesIntro:
    "Every creature that drops or can be harvested for something, and every trader, as far as the game's data declares it. Drops decided in code are not listed.",
  entitiesFilter: "Filter",
  entitiesFilterPlaceholder: "Name or code, e.g. wolf",
  entitiesNone: (q: string) => `No creature or trader matches “${q}”.`,
  creatures: "Creatures",
  traders: "Traders",
  entityCounts: (variants: number, drops: number, trades: number) =>
    [
      variants > 1 ? `${variants} variants` : "",
      drops ? `${drops} item${drops === 1 ? "" : "s"} dropped` : "",
      trades ? `${trades} item${trades === 1 ? "" : "s"} traded` : "",
    ]
      .filter(Boolean)
      .join(", "),
  variantsLabel: "Variants",
  allVariants: "All variants",
  allVariantsHint: (n: number) => `Every item the ${n} variants give, with the range of amounts. Pick a variant for its own list.`,
  everyVariant: "all",
  someVariants: (n: number, total: number) => `${n} of ${total}`,
  entityNotInVersion: (code: string, version: string) => `${code} gives nothing in version ${version}, or does not exist there.`,
  entitySections: {
    drops: "Drops when killed",
    harvest: "Harvested from the body",
    sells: "Sells",
    buys: "Buys",
  },
  item: "Item",
  stock: "Stock",
  perTrade: "Per trade",
  priceHeading: "Price in rusty gears",
  resultsFor: (q: string, n: number, more: boolean) =>
    `${more ? "More than " : ""}${n.toLocaleString("en")} result${n === 1 ? "" : "s"} for “${q}”`,
  noResults: (q: string) => `Nothing matches “${q}”.`,
  hiddenInHandbook: "not in handbook",
  code: "Code",
  mod: "Mod",
  kind: "Kind",
  description: "Description",
  attributes: "Properties",
  sources: "Other sources",
  madeBy: "Made by",
  usedIn: "Used in",
  noRecipesMake: "No recipe makes this item.",
  noRecipesUse: "No recipe uses this item.",
  smeltedFrom: "Obtained by heating",
  smeltsInto: "Heating it gives",
  itemNotInVersion: (code: string, version: string) => `${code} is not in version ${version}.`,
  keptItem: (code: string) => `Showing ${code} in the version you picked.`,
  lostItem: (code: string) => `${code} does not exist in that version, so you are on its start page.`,
  showMore: (n: number) => `Show ${n} more`,
  recipeCount: (n: number) => `${n} recipe${n === 1 ? "" : "s"}`,
  variantOf: (i: number, n: number) => `Variant ${i} of ${n}`,
  previousVariant: "Previous variant",
  nextVariant: "Next variant",
  pause: "Pause",
  play: "Play",
  shapeless: "Shapeless: any arrangement works",
  tool: "Tool",
  toolNote: (cost: number | undefined) => (cost ? `tool, loses ${cost} durability` : "tool, not consumed"),
  returns: (name: string) => `returns ${name}`,
  output: "Output",
  ingredients: "Ingredients",
  layer: "Layer",
  layerOf: (i: number, n: number) => `Layer ${i} of ${n}`,
  filledCells: (n: number) => `${n} filled`,
  voxelGrid: (w: number, h: number) => `${w} by ${h} pattern`,
  sealFor: (h: number) => `Seal for ${h} hour${h === 1 ? "" : "s"}`,
  noSeal: "Mixes instantly, no sealing",
  cooksInto: "Cooks into",
  dirtyPot: "Leaves the pot dirty",
  requirements: "Requirements",
  buildInPlace: "Place the block, then right-click it with each stage's items in your hotbar.",
  stage: (n: number) => `Stage ${n}`,
  stages: "Stages",
  placed: "Place it",
  construct: "Construct",
  rightClick: (action: string) => `Right-click: ${action}`,
  totalNeeded: "In total",
  ratio: "Share",
  amount: "Amount",
  slot: "Slot",
  from: "From",
  source: "Defined in",
  empty: "empty",
  nothingMatches: "nothing registered matches",
  row: (r: number, c: number) => `row ${r}, column ${c}`,
  credits: "Credits",
  creditsIntro:
    "Everything shown here comes from these mods and from the game itself, exported from a server running the pack. All names, text and images belong to their authors.",
  by: "by",
  unknownAuthors: "authors not listed",
  about: "About",
  aboutText:
    "This site is an unofficial fan project for the Seraph Horizons modpack. It is not made by, affiliated with or endorsed by Anego Studios, the developers of Vintage Story, or by the authors of the mods listed above.",
  removal: "Removal requests",
  removalText: "If you are the author of anything shown here and want it changed or removed, open an issue on the GitHub repository:",
  removalLink: "open an issue",
  sourceCode: "Source on GitHub",
  sourceKinds: {
    blockDrop: "Dropped by block",
    entityDrop: "Dropped by creature",
    traderSells: "Sold by trader",
    traderBuys: "Bought by trader",
    other: "Other",
  },
  // Kinds for sources of type `other`, by the export's note; the note then goes unsaid.
  sourceNotes: { Panned: "Panning", Harvested: "Harvested" } as Record<string, string>,
  panChance: "Chance on each pan",
  scalesWithStat: (stat: string) => `chance scales with player stat ${stat}`,
  andMore: (n: number) => `and ${n} more`,
  quantity: "Quantity",
  price: (gears: number) => `${gears} rusty gear${gears === 1 ? "" : "s"}`,
  attr: {
    maxStackSize: "Stack size",
    durability: "Durability",
    tool: "Tool type",
    toolTier: "Tool tier",
    requiredMiningTier: "Mining tier needed",
    attackPower: "Attack power",
    materialDensity: "Density",
    nutrition: "Nutrition",
    burn: "Fuel",
    smelting: "Heating",
    storageFlags: "Storage",
  },
  densityHint: (density: number) =>
    `${density <= 1000 ? "Floats" : "Sinks"} in water. Water's density is 1000: dropped items at or below it float, heavier ones sink.`,
  placeholderIcon: "no icon",
  modelsLink: "Models",
};

export type Strings = typeof en;
export const t: Strings = en;
