#!/usr/bin/env python3
"""Generate the soldered copper and lead pipes' shapes and the patch that puts them on ppex's pipes.

UnifiedPipes gives Pipes and Power Expanded's (ppex's) straight, bend, T- and X-junction pipes copper
and lead states (patches/unifiedpipes-ppex.json). ppex draws every pipe with an iron band and bolts at
its ends, which suits its cast, banded iron and steel; copper and lead pipe is soldered. This writes,
deterministically,

    shapes/block/pipes/soldered-{straight,bend,tjunction,xjunction}.json
        this mod's own model of each, built by solderedpipe.py: ppex's cross-section and texture
        code (`iron4`, which the copper and lead states texture as sheet-plain copper4 and lead4),
        no band or bolts, half a wiped joint of solder at each open end; each in the orientation of
        ppex's shape of that pipe, so ppex's rotations turn it the same way;
    patches/unifiedpipes-solderedjoints.json
        each pipe's `shapebytype` replaced by ppex's own table with a copper and a lead entry before
        each of its entries: the same rotations, this mod's shape. The game takes the first key that
        matches a block's code, so ppex's `*-...-*` entries go on serving iron and steel.

or, with `--out DIR`, all five into DIR. Run it after `python3 tools/packtool.py fetch`: it reads ppex's
blocktypes and shapes from build/mods/ppex_*.zip, checks the tube against ppex's (its cross-section in
the block, so the two meet flush) and its own boxes for overlaps and coplanar faces, and exits
non-zero if a check fails. The runtime guard is Pipes/Core/SolderedJoints.cs; tools/tests/
test_soldered_pipes.py holds the files to this script and to ppex's zip.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
import zipfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
sys.path.insert(0, str(Path(__file__).resolve().parents[2] / "Machines" / "tools"))

import solderedpipe as sp  # noqa: E402
from machinegen.geometry import flatten  # noqa: E402
from machinegen.output import shape_dumps  # noqa: E402

ROOT = Path(__file__).resolve().parents[4]
MOD = ROOT / "mods-src" / "seraphhorizons"
ASSETS = MOD / "assets" / "seraphhorizons"
SHAPE_DIR = ASSETS / "shapes" / "block" / "pipes"
PATCH_OUT = ASSETS / "patches" / "unifiedpipes-solderedjoints.json"
MODS_DIR = ROOT / "build" / "mods"
SCRIPT = "mods-src/seraphhorizons/Pipes/tools/make_pipe_shapes.py"

B = 16.0
MID = B / 2                                   # a pipe's axis: the middle of its block
METALS = ("copper", "lead")                   # the soldered metals (PipeRules.AddedPipeMaterials)
BODY_CODE = "iron4"                           # ppex's texture code, which the patch's copper and lead states texture
TEXTURES = {BODY_CODE: "game:block/metal/sheet-plain/copper4", "solder": sp.SOLDER_TEXTURE}
SHAPE_BASE = "seraphhorizons:block/pipes/soldered-{}"
# Each pipe in ppex's own orientation of its shape (its blocktype turns it): the arms it has.
PIPES = {
    "straight": ("north", "south"),
    "bend": ("north", "west"),
    "tjunction": ("west", "north", "east"),
    "xjunction": ("north", "east", "south", "west"),
}


def pipe_boxes(kind):
    """The boxes of one soldered pipe, in block voxels (0..16)."""
    arms = PIPES[kind]
    out = []
    if kind == "straight":
        out += sp.tube("pipe", 2, 0.0, B, (MID, MID))
    else:
        out += sp.hub("hub", (MID, MID, MID), arms)
        for arm in arms:
            k, sgn = sp.FACE_NORMAL[arm]
            u, v = sp.ACROSS[k]
            face, inner = (0.0, MID - sp.HALF) if sgn < 0 else (B, MID + sp.HALF)
            out += sp.tube(f"arm_{arm}", k, face, inner, (MID, MID))
    for arm in arms:
        k, sgn = sp.FACE_NORMAL[arm]
        face = 0.0 if sgn < 0 else B
        out += sp.half_joint(f"joint_{arm}", k, face, -sgn, (MID, MID))
    return sp.cull_pressed(out)


def element(box, codes, scale=1.0):
    """A box as a shape element: its texture code by role, explicit UVs."""
    size = box.size()
    return {"name": box.name, "from": [r4(v) for v in box.lo], "to": [r4(v) for v in box.hi],
            "faces": {d: {"texture": "#" + codes[box.role], "uv": sp.uv(d, size, scale)} for d in sp.FACES if d in box.faces}}


def r4(x):
    v = round(x, 4)
    return 0.0 if v == 0 else v


def shape(kind):
    return {
        "_comment": f"Generated by {SCRIPT} (solderedpipe.py): UnifiedPipes' copper and lead {kind} pipe, this mod's own "
                    "model on Pipes and Power Expanded's cross-section (a 6 x 6 tube with a 4 x 4 bore, its block's 5..11) in "
                    f"ppex's orientation of its {kind} shape, with half a wiped joint of solder at each open end in place of "
                    "ppex's iron band and bolts. The body's code is ppex's iron4, which the copper and lead states texture.",
        "textureWidth": 16, "textureHeight": 16,
        "textures": dict(TEXTURES),
        "elements": [element(b, {sp.BODY: BODY_CODE, sp.SOLDER: "solder"}) for b in pipe_boxes(kind)],
    }


# ---------------------------------------------------------------- the patch
def soldered_key(key):
    """ppex's `*-<type>-<orientation>-*` key for one metal: the trailing material wildcard named."""
    if not key.endswith("-*"):
        raise ValueError(f"ppex's shape key {key!r} does not end in its material wildcard")
    return lambda metal: key[:-1] + metal


def soldered_table(kind, table):
    """ppex's shapebytype table with each entry preceded by one per soldered metal: the same rotations,
    this mod's shape."""
    out = {}
    for key, value in table.items():
        named = soldered_key(key)
        for metal in METALS:
            out[named(metal)] = {**value, "base": SHAPE_BASE.format(kind)}
        out[key] = value
    return out


def patch_ops(ppex):
    """The patch's operations from ppex's blocktypes ({kind: parsed JSON})."""
    return [{"file": f"ppex:blocktypes/pipes/{kind}.json", "op": "replace", "path": "/shapebytype",
             "value": soldered_table(kind, ppex[kind]["shapebytype"]), "dependsOn": [{"modid": "ppex"}]}
            for kind in PIPES]


PATCH_HEADER = """\
// seraphhorizons' UnifiedPipes switch (README.md "Unified pipes"): copper and lead pipe is soldered, so
// Pipes and Power Expanded's straight, bend, T- and X-junction pipes in copper and lead (the states
// unifiedpipes-ppex.json adds) are drawn on this mod's own models, shapes/block/pipes/soldered-*.json:
// ppex's cross-section, no iron band or bolts, half a wiped joint of solder at each open end. Each
// pipe's shapebytype is ppex's table with a copper and a lead entry before each of its entries, with
// that entry's rotations; the game takes the first key matching a block's code, so ppex's entries go on
// serving iron and steel. Generated by mods-src/seraphhorizons/Pipes/tools/make_pipe_shapes.py from
// ppex's zip (0.7.1); do not edit by hand. UnifiedPipesSystem checks each table against ppex's before
// the patch loader runs (Pipes/Core/SolderedJoints.cs) and empties this file alone with one warning
// when ppex has changed one (its copper and lead pipes then keep ppex's banded model), or with the
// switch off; tools/tests/test_soldered_pipes.py holds it to ppex's zip.
"""


def patch_dumps(ops):
    lines = ["["]
    for i, op in enumerate(ops):
        lines.append("  {")
        lines.append(f'    "file": {json.dumps(op["file"])}, "op": {json.dumps(op["op"])}, "path": {json.dumps(op["path"])},')
        lines.append('    "value": {')
        entries = list(op["value"].items())
        for j, (k, v) in enumerate(entries):
            lines.append(f"      {json.dumps(k)}: {json.dumps(v, separators=(', ', ': '))}" + ("," if j < len(entries) - 1 else ""))
        lines.append("    },")
        lines.append(f'    "dependsOn": {json.dumps(op["dependsOn"], separators=(", ", ": "))}')
        lines.append("  }" + ("," if i < len(ops) - 1 else ""))
    lines.append("]")
    return PATCH_HEADER + "\n".join(lines) + "\n"


# ---------------------------------------------------------------- ppex and the checks
def load_ppex(mods_dir=MODS_DIR):
    """ppex's pipe blocktypes and shapes from its zip: ({kind: blocktype}, {kind: shape}, zip name)."""
    zips = sorted(mods_dir.glob("ppex_*.zip"))
    if not zips:
        raise SystemExit(f"no ppex_*.zip in {mods_dir}: run `python3 tools/packtool.py fetch`")
    blocktypes, shapes = {}, {}
    with zipfile.ZipFile(zips[-1]) as z:
        for kind in PIPES:
            blocktypes[kind] = json.loads(z.read(f"assets/ppex/blocktypes/pipes/{kind}.json").decode("utf-8-sig"))
            shapes[kind] = json.loads(z.read(f"assets/ppex/shapes/pipes/{kind}.json").decode("utf-8-sig"))
    return blocktypes, shapes, zips[-1].name


def section_at(boxes, axis, at, step=0.25):
    """The cells of a 1/4-voxel grid across the block that the boxes ((lo, hi) pairs) cover at `at`
    along `axis`."""
    u, v = sp.ACROSS[axis]
    out = set()
    for i in range(int(B / step)):
        for j in range(int(B / step)):
            p = [0.0] * 3
            p[axis], p[u], p[v] = at, (i + 0.5) * step, (j + 0.5) * step
            if any(all(lo[k] < p[k] < hi[k] for k in range(3)) for lo, hi in boxes):
                out.add((i, j))
    return out


def ring_section(axis):
    """A pipe's section across `axis` on the 1/4-voxel grid: the 6 x 6 tube less its 4 x 4 bore."""
    lo, hi = [MID - sp.HALF] * 3, [MID + sp.HALF] * 3
    bore_lo, bore_hi = [MID - sp.HALF + sp.WALL] * 3, [MID + sp.HALF - sp.WALL] * 3
    lo[axis], hi[axis] = bore_lo[axis], bore_hi[axis] = -1.0, B + 1
    return section_at([(lo, hi)], axis, MID) - section_at([(bore_lo, bore_hi)], axis, MID)


def check(blocktypes, shapes):
    """The checks: every shape's boxes clean (no overlaps, no coplanar faces, unique names, inside
    the block); at every arm's end, under its joint, the pipe is the tube round an open bore; the
    straight's tube is ppex's where ppex's has no band (half a block in); every ppex table key ends in
    its material wildcard and names ppex's shape of that pipe."""
    bad = []
    for kind in PIPES:
        boxes = pipe_boxes(kind)
        bad += [f"{kind}: {p}" for p in sp.check(boxes)]
        if len({b.name for b in boxes}) != len(boxes):
            bad.append(f"{kind}: element names repeat")
        if any(b.lo[k] < 0 or b.hi[k] > B for b in boxes for k in range(3)):
            bad.append(f"{kind}: a box leaves the block")
        body = [(b.lo, b.hi) for b in boxes if b.role == sp.BODY]
        for arm in PIPES[kind]:
            k, sgn = sp.FACE_NORMAL[arm]
            at = 0.1 if sgn < 0 else B - 0.1
            if section_at(body, k, at) != ring_section(k):
                bad.append(f"{kind}: the {arm} end is not the tube round an open bore")
        for key, value in blocktypes[kind]["shapebytype"].items():
            if not key.endswith("-*") or value.get("base") != f"ppex:pipes/{kind}":
                bad.append(f"{kind}: ppex's entry {key} is not its {kind} shape by material")
    # ppex's straight tube at mid-length (no band there) against ours
    ours = [(b.lo, b.hi) for b in pipe_boxes("straight") if b.role == sp.BODY]
    theirs = [el.aabb() for el in flatten(shapes["straight"]["elements"], textures={})
              if all(f.get("texture") == "#iron4" for f in el.faces.values())]
    if section_at(ours, 2, MID) != section_at(theirs, 2, MID) or section_at(ours, 2, MID) != ring_section(2):
        bad.append("straight: the tube's cross-section is not ppex's")
    return bad


def ppex_band(shape):
    """ppex's band and bolts: its elements in the corroded iron texture (normal4)."""
    return [el.name for el in flatten(shape["elements"], textures={}) if any(f.get("texture") == "#normal4" for f in el.faces.values())]


def main():
    ap = argparse.ArgumentParser(description="Generate the soldered copper and lead pipes' shapes and their patch.")
    ap.add_argument("--out", type=Path, help="write the files into this directory instead of the mod's assets")
    args = ap.parse_args()
    blocktypes, shapes, source = load_ppex()
    bad = check(blocktypes, shapes)
    print(f"the tube at mid-length: ppex's section {'is' if not any('cross-section' in b for b in bad) else 'is NOT'} ours "
          f"({len(ring_section(2))} quarter-voxel cells: 6 x 6 round a 4 x 4 bore)")
    for kind in PIPES:
        n = len(shape(kind)["elements"])
        print(f"{kind}: {n} elements (ppex's: {len(flatten(shapes[kind]['elements'], textures={}))}, "
              f"{len(ppex_band(shapes[kind]))} of them band and bolts); {len(blocktypes[kind]['shapebytype'])} orientations")
    texts = {SHAPE_DIR / f"soldered-{kind}.json": shape_dumps(shape(kind)) for kind in PIPES}
    texts[PATCH_OUT] = patch_dumps(patch_ops(blocktypes))
    for path, text in texts.items():
        out = args.out / path.name if args.out else path
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(text)
        json.loads(re.sub(r"^//.*$", "", out.read_text(), flags=re.M))
        print(f"wrote {out}")
    print(f"from {source}")
    if bad:
        for b in bad:
            print("FAIL:", b)
        sys.exit(1)
    print("all checks passed")


if __name__ == "__main__":
    main()
